FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY backend/package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY backend ./
#COPY backend/src ./src
#COPY backend/tsconfig.json ./

# Expose port
EXPOSE 5000

# Start development server
CMD ["npm", "run", "dev"]