FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY frontend ./
##COPY frontend/public ./public
##COPY frontend/src ./src
##COPY frontend/tsconfig.json ./
##COPY frontend/tailwind.config.js ./
##COPY frontend/postcss.config.js ./

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "start"]